### PR TITLE
Trying to fix https://github.com/d6lts/drupal/issues/52 : back to a s…

### PR DESCRIPTION
**Pull request by ylp-ineris**
…ingle table name prefix while quoting all table names with backticks (and not just table names which are keywords in MySQL 8+)

### CODE REVIEW

**Comment by dsnopek** [comment]
Thanks for the PR!

However, I don't think we want to quote all table names with backticks. Only messing with table names that were reserved keywords was a compromise that we struck when implementing the MySQL 8 changes, and I don't see a compelling reason to go back on that compromise.

**Comment by ylp-ineris** [comment]
Ok, a new proposal whith the last commit. It is a way to only quote MySQL 8 keywords-like table names while fixing https://github.com/d6lts/drupal/issues/52

Maybe the heavier modification this 2 steps treatment involves is a _compelling reason to go back on that compromise_? Maybe not :)

Note that I haven't test this version (the previous is in production on one of the website I am in charge of).

**Comment by dsnopek** [comment]
Sorry for taking so long to get back to this! I finally had a chance to test your PR in bunch of different cases and it works great. :-)

**Comment by ylp-ineris** [comment]
Cool!
And I see it’s part of Drupal 6.58… I’m happy to be a contributor of Drupal 6!

De : David Snopek ***@***.***>
Envoyé : jeudi 1 juillet 2021 21:55
À : d6lts/drupal ***@***.***>
Cc : LE-PAPE Yannick ***@***.***>; Author ***@***.***>
Objet : Re: [d6lts/drupal] Trying to fix https://github.com/d6lts/drupal/issues/52 : back to a s… (#55)


Sorry for taking so long to get back to this! I finally had a chance to test your PR in bunch of different cases and it works great. :-)

**Pull request merged**
